/* Generated By:JavaCC: Do not edit this line. BooleanParserConstants.java */
package com.mesut.bool.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BooleanParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ZERO = 1;
  /** RegularExpression Id. */
  int ONE = 2;
  /** RegularExpression Id. */
  int LPAREN = 3;
  /** RegularExpression Id. */
  int RPAREN = 4;
  /** RegularExpression Id. */
  int LBRACE = 5;
  /** RegularExpression Id. */
  int RBRACE = 6;
  /** RegularExpression Id. */
  int LBRACKET = 7;
  /** RegularExpression Id. */
  int RBRACKET = 8;
  /** RegularExpression Id. */
  int SEMICOLON = 9;
  /** RegularExpression Id. */
  int COLON = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int QUOTE = 12;
  /** RegularExpression Id. */
  int EQ = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int DIV = 15;
  /** RegularExpression Id. */
  int AND = 16;
  /** RegularExpression Id. */
  int OR = 17;
  /** RegularExpression Id. */
  int XOR = 18;
  /** RegularExpression Id. */
  int NOR = 19;
  /** RegularExpression Id. */
  int NAND = 20;
  /** RegularExpression Id. */
  int XNOR = 21;
  /** RegularExpression Id. */
  int NOT = 22;
  /** RegularExpression Id. */
  int IDENT = 23;
  /** RegularExpression Id. */
  int CHAR = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"0\"",
    "\"1\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"\\\'\"",
    "\"=\"",
    "\"-\"",
    "\"/\"",
    "<AND>",
    "<OR>",
    "<XOR>",
    "\"nor\"",
    "\"nand\"",
    "\"xnor\"",
    "\"not\"",
    "<IDENT>",
    "<CHAR>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"~\"",
    "\"!\"",
  };

}
