/* Generated By:JavaCC: Do not edit this line. BooleanParserConstants.java */
package com.mesut.bool.parser2;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BooleanParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ZERO = 5;
  /** RegularExpression Id. */
  int ONE = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int LBRACE = 10;
  /** RegularExpression Id. */
  int RBRACE = 11;
  /** RegularExpression Id. */
  int LBRACKET = 12;
  /** RegularExpression Id. */
  int RBRACKET = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int COLON = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int QUOTE = 17;
  /** RegularExpression Id. */
  int EQ = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int DIV = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int XOR = 23;
  /** RegularExpression Id. */
  int NOR = 24;
  /** RegularExpression Id. */
  int NAND = 25;
  /** RegularExpression Id. */
  int XNOR = 26;
  /** RegularExpression Id. */
  int NOT = 27;
  /** RegularExpression Id. */
  int IDENT = 28;
  /** RegularExpression Id. */
  int CHAR = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"0\"",
    "\"1\"",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"\\\'\"",
    "\"=\"",
    "\"-\"",
    "\"/\"",
    "<AND>",
    "<OR>",
    "<XOR>",
    "\"nor\"",
    "\"nand\"",
    "\"xnor\"",
    "\"not\"",
    "<IDENT>",
    "<CHAR>",
    "\"~\"",
    "\"!\"",
  };

}
