#!/bin/bash

dir=$(dirname $0)

grammar="${dir}/boolean.jj"
out="${dir}/../src/com/mesut/bool/parser"
#cc="/storage/extSdCard/lib/javacc-7.0.5.jar"
cc="/home/mesut/Desktop/lib/javacc-7.0.5.jar"

java -cp $cc javacc -OUTPUT_DIRECTORY=${out} -FORCE_LA_CHECK=true $grammar
